version: "3"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ="Europe/Paris"
      - PLEX_CLAIM="claim-xxxxxxxxxxxxxx"
      - ADVERTISE_IP="http://plex.example.com:32400/"
      - PLEX_UID=ubuntu
      - PLEX_GID=ubuntu
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ./data:/data
    hostname: plex.pej.ovh
    #network_mode: host
    #    ports:
    # - 32400:32400/tcp
    # - 3005:3005/tcp
    # - 8324:8324/tcp
    # - 32469:32469/tcp
    # - 1900:1900/udp
    # - 32410:32410/udp
    # - 32412:32412/udp
    # - 32413:32413/udp
    # - 32414:32414/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=32400"
      - "traefik.frontend.rule=Host:plex.example.com"


  traefik:
    network_mode: host
    restart: unless-stopped
    image: traefik:v1.7.16
    read_only: true
    command:  --web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./traefik.toml:/traefik.toml
    labels:
      - 'traefik.frontend.rule=Host:plex.example.com'
      - 'traefik.port=8080'
      - 'traefik.enable=true'
      - 'traefik.backend=web'
